title: [Ninebot MAX G2 SHFW Settings]
description: [SHFW settings and instructions]
show_downloads: ["false"]
google_analytics: [G-R8SLS8JP95]
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme